export const categories = [
  { name: 'Phấn Trang Điểm', slug: 'phan-trang-diem' },
  { name: 'Dầu Gội - Dưỡng Tóc', slug: 'dau-goi-duong-toc' },
  { name: 'Kẻ Mắt - Eyeliner', slug: 'ke-mat-eyeliner' },
  { name: 'Son Môi', slug: 'son-moi' },
  { name: 'Kẻ Chân Mày - Màu Mắt - Má Hồng', slug: 'ke-chan-may-mau-mat-ma-hong' },
  { name: 'Mascara', slug: 'mascara' },
  { name: 'Kem Nền - BB Cream', slug: 'kem-nen-bb-cream' },
  { name: 'Nước Hoa Hồng - Xịt Khoáng', slug: 'nuoc-hoa-hong-xit-khoang' },
  { name: 'Sữa Rửa Mặt - Tẩy Trang', slug: 'sua-rua-mat-tay-trang' },
  { name: 'Dụng Cụ Trang Điểm - Làm Đẹp', slug: 'dung-cu-trang-diem-lam-dep' },
  { name: 'Trị Mụn - Sẹo - Thâm - Nám', slug: 'tri-mun-seo-tham-nam' },
  { name: 'Dưỡng Da - Serum', slug: 'duong-da-serum' },
  { name: 'Mặt Nạ - Tẩy Tế Bào Chết', slug: 'mat-na-tay-te-bao-chet' },
  { name: 'Che Khuyết Điểm - Highlight', slug: 'che-khuyet-diem-highlight' },
  { name: 'Xà Phòng - Sữa Tắm', slug: 'xa-phong-sua-tam' },
  { name: 'Chống Nắng - Make Up Body', slug: 'chong-nang-make-up-body' },
  { name: 'Kem Tẩy Lông - Tẩy Trắng Răng', slug: 'kem-tay-long-tay-trang-rang' },
  { name: 'Xịt Body - Dưỡng Body', slug: 'xit-body-duong-body' },
  { name: 'Thực Phẩm Chức Năng', slug: 'thuc-pham-chuc-nang' },
  { name: 'Tan Mỡ - Rạn Da', slug: 'tan-mo-ran-da' },
  { name: 'Dưỡng Mắt - Dưỡng Mi - Dưỡng Tay', slug: 'duong-mat-duong-mi-duong-tay' },
]

export const sampleProducts = [
  { name: 'Kem Chống Nắng Neutrogena Beach Defense SPF 70', slug: 'kem-chong-nang-neutrogena-spf70', price: 185000, oldPrice: 200000, categorySlug: 'chong-nang-make-up-body', imageUrl: 'http://taingo.ddns.net/2015/myphamnhatrang/images/upload/item/item_57aad5b8de344.jpg', description: 'Kem chống nắng Neutrogena Beach Defense SPF 70+ bảo vệ làn da khỏi ánh nắng khắc nghiệt. Chống thấm nước 80 phút, không chứa dầu và Parabens.', featured: true },
  { name: 'Son Bourjois Rouge Edition Velvet', slug: 'son-bourjois-rouge-edition-velvet', price: 220000, oldPrice: 250000, categorySlug: 'son-moi', imageUrl: '', description: 'Son lì cao cấp từ Pháp, lên màu chuẩn, lâu trôi.', featured: true },
  { name: 'Son kem lì L.A Girl Matte Flat Finish', slug: 'son-kem-li-la-girl-matte', price: 100000, oldPrice: 115000, categorySlug: 'son-moi', imageUrl: '', description: 'Son kem lì màu sắc đa dạng, lên màu đẹp.', featured: true },
  { name: 'Sữa Rửa Mặt Innisfree Green Tea Pure Cleansing Foam', slug: 'sua-rua-mat-innisfree-green-tea', price: 165000, oldPrice: 180000, categorySlug: 'sua-rua-mat-tay-trang', imageUrl: '', description: 'Sữa rửa mặt trà xanh Innisfree làm sạch sâu, dưỡng ẩm.', featured: true },
  { name: 'Serum Trà Xanh Innisfree Green Tea Seed', slug: 'serum-tra-xanh-innisfree', price: 320000, oldPrice: 350000, categorySlug: 'duong-da-serum', imageUrl: '', description: 'Serum dưỡng ẩm chuyên sâu từ hạt trà xanh Innisfree.', featured: true },
  { name: 'Mặt Nạ Ngủ Trà Xanh Innisfree Green Tea Sleeping Pack', slug: 'mat-na-ngu-tra-xanh-innisfree', price: 195000, oldPrice: 220000, categorySlug: 'mat-na-tay-te-bao-chet', imageUrl: '', description: 'Mặt nạ ngủ cấp ẩm tối ưu trong khi ngủ.', featured: false },
  { name: 'Mascara 4D Dimension Mistine', slug: 'mascara-4d-dimension-mistine', price: 40000, oldPrice: 70000, categorySlug: 'mascara', imageUrl: '', description: 'Mascara làm dày mi, không lem.', featured: false },
  { name: 'Phấn Nước A\'pieu Air Fit Cushion SPF50+', slug: 'phan-nuoc-apieu-air-fit-cushion', price: 165000, oldPrice: 170000, categorySlug: 'phan-trang-diem', imageUrl: '', description: 'Phấn nước che phủ hoàn hảo, chống nắng SPF50+.', featured: true },
  { name: 'Kem Tẩy Lông Veet 100ml', slug: 'kem-tay-long-veet-100ml', price: 100000, oldPrice: 115000, categorySlug: 'kem-tay-long-tay-trang-rang', imageUrl: '', description: 'Kem tẩy lông Veet nhập khẩu từ Pháp, an toàn cho da.', featured: false },
  { name: 'Chì Kẻ Mày The Face Shop Design My Eyebrow', slug: 'chi-ke-may-the-face-shop', price: 40000, oldPrice: 45000, categorySlug: 'ke-chan-may-mau-mat-ma-hong', imageUrl: '', description: 'Chì kẻ mày ngang tiện lợi, tự nhiên.', featured: false },
  { name: 'Gel Dưỡng Tóc Mise En Scene Perfect Repair', slug: 'gel-duong-toc-mise-en-scene', price: 130000, oldPrice: 140000, categorySlug: 'dau-goi-duong-toc', imageUrl: '', description: 'Gel dưỡng tóc phục hồi tóc hư tổn.', featured: false },
  { name: 'Nước Tẩy Trang Micellar Water Garnier', slug: 'nuoc-tay-trang-garnier-micellar', price: 95000, oldPrice: 110000, categorySlug: 'sua-rua-mat-tay-trang', imageUrl: '', description: 'Nước tẩy trang nhẹ dịu, sạch sâu.', featured: true },
]
